import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MainNav } from "@/components/mainnav";
import LeftSidebar from "@/components/LeftSidebar";
import { Footer } from "@/components/footer";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <div className="flex flex-col min-h-screen">
            <MainNav />
            <div className="md:flex-1 md:flex-row md:flex flex flex-col">
              <LeftSidebar />
              <div className="md:px-20 px-2 overflow-x-hidden my-4">
                {children}
                {/* <div className="w-64 overflow-auto scroll-smooth scrollbar-hide h-svh">
                <div>right</div>
              </div> */}
              </div>
            </div>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
