import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MainNav } from "@/components/mainnav";
import LeftSidebar from "@/components/LeftSidebar";
import { Footer } from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen">
          <MainNav />
          <div className="flex-1 flex">
            <LeftSidebar />
            <div className="flex-1 px-20">
              {children}
              {/* <div className="w-64 overflow-auto scroll-smooth scrollbar-hide h-svh">
                <div>right</div>
              </div> */}
            </div>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
